// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavxlxrttdcqbknhxiph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdnhseHJ0dGRjcWJrbmh4aXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzcxMzQsImV4cCI6MjA2OTQ1MzEzNH0.UhWBAi2Gt-ktERqMWqEEOyZUQHnLW3Zy749YIFZBAog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});